git:
  overrideGpg: true
  paging:
    colorArg: always
    pager: delta --dark --paging=never --line-numbers
customCommands:
  - key: "o"
    command: "hub browse -- tree/main"
    context: "localBranches"
  - key: "o"
    command: "hub browse -- tree/main"
    context: "global"
  - key: "n"
    prompts:
      - type: "menu"
        title: "What kind of branch is it? (from {{ index .SelectedLocalBranch.Name }})"
        options:
          - name: "julian.grande"
            value: "julian.grande"
            description: "Prefix with my name"
          - name: "feature"
            value: "feat"
            description: "A new feature"
          - name: "fix"
            value: "fix"
            description: "Fix for broken functionality"
          - name: "documentation"
            value: "docs"
            description: "Update to `README` or code comments"
          - name: "refactor"
            value: "refactor"
          - name: "test"
            value: "test"
            description: "New or update to existing tests"
          - name: "chore"
            value: "chore"
            description: "Upgrading packages, updating conf etc."
          - name: "build"
            value: "build"
          - name: "CI/CD"
            value: "ci"
            description: "Pipelines"
      - type: "input"
        title: "What is the {{index .PromptResponses 0}} name?"
        initialValue: ""
    command: "git checkout -b {{index .PromptResponses 0}}/{{index .PromptResponses 1}}"
    context: "localBranches"
    loadingText: "creating branch"
